project:
  type: website

website:
  title: "Taller de revisi√≥n de software por pares en rOpenSci"
  navbar:
    left:
      - href: site.qmd
        text: Home
  sidebar:
    style: "docked"
    search: true
    contents:
      - site.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: false
