project:
  type: book

book:
  title: "Taller de revisi√≥n de software por pares en rOpenSci"
  author: "Mauro Lepore"
  date: last-modified
  chapters:
    - book.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: false
